[misc] Update core dependencies.

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -29,6 +29,7 @@ jobs:
           - OS: 'macos-13'
             PYTHON_VERSION: '3.11'
             BUILD_TYPE: 'Debug'
+            LINKER_FLAGS: '-Wl,-ld_classic'  # New "ld_prime" linker (XCode 15+) causes build failures
 
     runs-on: ${{ matrix.OS }}
 
@@ -37,9 +38,9 @@ jobs:
         shell: bash -ieo pipefail {0}
 
     env:
-      CMAKE_C_COMPILER: "/usr/bin/clang"
-      CMAKE_CXX_COMPILER: "/usr/bin/clang++"
-      CMAKE_CXX_FLAGS: "-DEIGEN_MPL2_ONLY -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION -Wno-deprecated-declarations"
+      C_COMPILER: "/usr/bin/clang"
+      CXX_COMPILER: "/usr/bin/clang++"
+      CXX_FLAGS: "-DEIGEN_MPL2_ONLY -Wno-deprecated-declarations"
       OSX_DEPLOYMENT_TARGET: "11.0"
       OSX_ARCHITECTURES: "x86_64;arm64"
       WHEEL_ARCH: "universal2"
@@ -76,11 +77,12 @@ jobs:
         "${PYTHON_EXECUTABLE}" -m pip install "gymnasium>=0.28,<1.0" "stable_baselines3>=2.0"
     - name: Install latest numpy version at build-time for run-time binary compatibility
       run: |
-        "${PYTHON_EXECUTABLE}" -m pip install --upgrade "numpy>=1.24,<2.0"
+        "${PYTHON_EXECUTABLE}" -m pip install --upgrade "numpy>=1.24"
     - name: Build jiminy dependencies
       run: |
         OSX_DEPLOYMENT_TARGET=${OSX_DEPLOYMENT_TARGET} OSX_ARCHITECTURES=${OSX_ARCHITECTURES} \
-          BUILD_TYPE="${{ matrix.BUILD_TYPE }}" ./build_tools/build_install_deps_unix.sh
+        LINKER_FLAGS="${{ matrix.LINKER_FLAGS }}" BUILD_TYPE="${{ matrix.BUILD_TYPE }}" \
+          ./build_tools/build_install_deps_unix.sh
 
     #####################################################################################
 
@@ -93,8 +95,10 @@ jobs:
         cd "${RootDir}/build"
         export LD_LIBRARY_PATH="${InstallDir}/lib/:/usr/local/lib"
         cmake "${RootDir}" -Wdev \
+              -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.LINKER_FLAGS }}" \
+              -DCMAKE_SHARED_LINKER_FLAGS="${{ matrix.LINKER_FLAGS }}" \
               -DCMAKE_INSTALL_PREFIX="${InstallDir}" -DCMAKE_PREFIX_PATH="${InstallDir}" \
-              -DCMAKE_C_COMPILER="${CMAKE_C_COMPILER}" -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER}" \
+              -DCMAKE_C_COMPILER="${C_COMPILER}" -DCMAKE_CXX_COMPILER="${CXX_COMPILER}" \
               -DCMAKE_OSX_ARCHITECTURES="${OSX_ARCHITECTURES}" \
               -DCMAKE_OSX_DEPLOYMENT_TARGET="${OSX_DEPLOYMENT_TARGET}" \
               -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
@@ -103,7 +107,7 @@ jobs:
               -DBoost_USE_STATIC_LIBS=ON -DPYTHON_EXECUTABLE="${PYTHON_EXECUTABLE}" \
               -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON -DBUILD_PYTHON_INTERFACE=ON \
               -DINSTALL_GYM_JIMINY=${{ (matrix.PYTHON_VERSION == '3.13' && 'OFF') || 'ON' }} \
-              -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}" -DCMAKE_BUILD_TYPE="${{ matrix.BUILD_TYPE }}"
+              -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DCMAKE_BUILD_TYPE="${{ matrix.BUILD_TYPE }}"
         make -j2
 
         # Bundle the boost python dependencies with jiminy
@@ -126,11 +130,17 @@ jobs:
         export DYLD_FALLBACK_LIBRARY_PATH="${LD_LIBRARY_PATH}"
 
         # Generate stubs
+        # FIXME: stubgen does not work with Numpy 2.X
+        # (see https://github.com/python/mypy/issues/17396)
+        "${PYTHON_EXECUTABLE}" -m pip install "numpy<2.0"
         stubgen -p jiminy_py -o ${RootDir}/build/pypi/jiminy_py/src
-        "${PYTHON_EXECUTABLE}" "${RootDir}/build_tools/stub_gen.py" \
-          -o ${RootDir}/build/stubs --ignore-invalid=all jiminy_py
-        cp ${RootDir}/build/stubs/jiminy_py-stubs/core/__init__.pyi \
-           ${RootDir}/build/pypi/jiminy_py/src/jiminy_py/core/core.pyi
+        # FIXME: Python 3.10 on Intel x86-64 crashes when generating stubs without any backtrace...
+        if [[ ("${{ matrix.OS }}" != 'macos-13') || ("${{ matrix.PYTHON_VERSION }}" != '3.10') ]] ; then
+          "${PYTHON_EXECUTABLE}" "${RootDir}/build_tools/stubgen.py" \
+            -o ${RootDir}/build/stubs --ignore-invalid=all jiminy_py
+          cp ${RootDir}/build/stubs/jiminy_py-stubs/core/__init__.pyi \
+             ${RootDir}/build/pypi/jiminy_py/src/jiminy_py/core/core.pyi
+        fi
 
         # Generate wheels
         cd "${RootDir}/build"
@@ -159,10 +169,13 @@ jobs:
 
         mkdir -p "${RootDir}/core/examples/external_project/build"
         cd "${RootDir}/core/examples/external_project/build"
-        cmake "${RootDir}/core/examples/external_project/" -DCMAKE_INSTALL_PREFIX="${InstallDir}" \
-              -DCMAKE_C_COMPILER="${CMAKE_C_COMPILER}" -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER}" \
-              -DCMAKE_PREFIX_PATH="${InstallDir}" -DPYTHON_EXECUTABLE="${PYTHON_EXECUTABLE}" \
-              -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}" -DCMAKE_BUILD_TYPE="${{ matrix.BUILD_TYPE }}"
+        cmake "${RootDir}/core/examples/external_project/" \
+              -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.LINKER_FLAGS }}" \
+              -DCMAKE_SHARED_LINKER_FLAGS="${{ matrix.LINKER_FLAGS }}" \
+              -DCMAKE_C_COMPILER="${C_COMPILER}" -DCMAKE_CXX_COMPILER="${CXX_COMPILER}" \
+              -DCMAKE_INSTALL_PREFIX="${InstallDir}" -DCMAKE_PREFIX_PATH="${InstallDir}" \
+              -DPYTHON_EXECUTABLE="${PYTHON_EXECUTABLE}" \
+              -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DCMAKE_BUILD_TYPE="${{ matrix.BUILD_TYPE }}"
         make install
 
         "${InstallDir}/bin/pip_double_pendulum"
@@ -201,7 +214,7 @@ jobs:
 
   publish-pypi-macos:
     name: (MacOS CI) Publish on PyPi the wheel for OS X of jiminy_py
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-24.04
     permissions:
       id-token: write
 
@@ -216,7 +229,7 @@ jobs:
         merge-multiple: true
         path: wheelhouse
     - name: Publish the wheel
-      uses: pypa/gh-action-pypi-publish@v1.8.11
+      uses: pypa/gh-action-pypi-publish@v1.10.3
       with:
         packages-dir: wheelhouse
         verify-metadata: false
