[gym] Split gym_jiminy in multiple packages (#218)
* [misc] Add copyright Pinocchio when necessary.
* [misc] Do not start URDF with comments since it is not properly supported.
* [misc] Cleanup unit test cmake config.
* [misc] Add support of ASCII art diagram in docs.
* [misc] More robust and versatile cmake pip install and wheel generation helpers.
* [misc] Improve CI scripts and remove warnings during build docs.
* [core] Use collisionResults instead of distanceResults to compute collisions for efficiency. Use 5 contact points by default.
* [core] More robust normal and penetration depth handling for collisions.
* [core] Fix edge case where the controller could be updated twise successively.
* [core/python] Fix controller functor q/v type to avoid creating Eigen::Ref for nothing.
* [core|python] Do not overwrite meshScale for convex, just ignore it when loading in viewer.
* [python] Various minor style improvements. Fix 'gcd' for float.
* [python/viewer] Properly initialize default backend viewer.
* [python/meshcat] Enable specifying custom material type when load geometry.
* [python/meshcat] Delete robot by-ground instead of by-element.
* [python/meshcat] Enable to visualize FCL BVHModelOBBRSS meshes. Use group to enable/disable 'visible' property. Fix client opening.
* [python|gym] Use Python namespace to enable installing components individually. Add new learning toolbox module.
* [gym] Add global option to enable/disable obs/action finite bounds.
* [gym] Use np.float32 for obs/action spaces.
* [gym] Add 'controller_dt' attribute and 'compute_command' method. Rename '_setup_environment' in '_setup'.
* [gym] Add new 'BaseController' base controller and 'ControlledJiminyEnv' [env + controller] wrapper. 
* [gym] Add 'PDController' block and use it in zoo envs.
* [gym] Update docs.

Co-authored-by: Alexis Duburcq <alexis.duburcq@wandercraft.eu>

diff --git a/.github/workflows/manylinux.yml b/.github/workflows/manylinux.yml
--- a/.github/workflows/manylinux.yml
+++ b/.github/workflows/manylinux.yml
@@ -15,7 +15,7 @@ jobs:
 
     defaults:
       run:
-        shell: bash
+        shell: bash -ieo pipefail {0}  # Using bash enables automatic sourcing `.bashrc` and fail-fast behavior
 
     env:
       BUILD_TYPE: "Release"
@@ -28,24 +28,26 @@ jobs:
 
     steps:
     - name: Checkout jiminy
-      uses: actions/checkout@v1 # Cannot use v2 in manylinux2010 container because it relies on node+javascript
+      uses: actions/checkout@v1  # Cannot use v2 in manylinux2010 container because it relies on node+javascript
 
     #####################################################################################
 
     - name: Setup minimal build environment
       run: |
         pythonLocation=$(find /opt/python -maxdepth 1 -name "$(echo "*${{ matrix.PYTHON_VERSION }}*" | sed -e 's/\.//g')" -print -quit)
+
         echo "export PATH=\"${pythonLocation}/bin:\$PATH\"" >> $HOME/.bashrc
         source $HOME/.bashrc
-        git config --global advice.detachedHead false
+
         PYTHON_EXECUTABLE="${pythonLocation}/bin/python${{ matrix.PYTHON_VERSION }}"
         "${PYTHON_EXECUTABLE}" -m pip install --upgrade pip
         "${PYTHON_EXECUTABLE}" -m pip install twine wheel
         "${PYTHON_EXECUTABLE}" -m pip install cmake numpy
         echo "PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}" >> $GITHUB_ENV
+
+        git config --global advice.detachedHead false
     - name: Build project dependencies
       run: |
-        source $HOME/.bashrc
         ./build_tools/build_install_deps_linux.sh
 
     #####################################################################################
@@ -55,7 +57,6 @@ jobs:
         RootDir="${GITHUB_WORKSPACE}"
         InstallDir="$RootDir/install"
 
-        source $HOME/.bashrc
         unset Boost_ROOT
 
         mkdir "$RootDir/build"
@@ -80,13 +81,13 @@ jobs:
         RootDir="${GITHUB_WORKSPACE}"
         InstallDir="$RootDir/install"
 
-        source $HOME/.bashrc
         export LD_LIBRARY_PATH="$InstallDir/lib:/usr/local/lib"
 
         cd "$RootDir/build"
         cmake . -DCOMPONENT=pypi -P ./cmake_install.cmake
-        auditwheel repair pypi/jiminy_py/dist/*.whl
-        "${PYTHON_EXECUTABLE}" -m pip install --force-reinstall --no-deps wheelhouse/*.whl
+
+        auditwheel repair -w "$RootDir/build/wheelhouse" "$RootDir"/build/pypi/jiminy_py/dist/*.whl
+        "${PYTHON_EXECUTABLE}" -m pip install --force-reinstall --no-deps "$RootDir"/build/wheelhouse/*.whl
     - name: Upload the wheel for Linux of Jiminy_py
       if: success() && github.repository == 'Wandercraft/jiminy'
       uses: actions/upload-artifact@v1
@@ -101,9 +102,10 @@ jobs:
         RootDir="${GITHUB_WORKSPACE}"
         InstallDir="$RootDir/install"
 
-        source $HOME/.bashrc
+        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$InstallDir/lib:/usr/local/lib"
 
-        LD_LIBRARY_PATH="$InstallDir/lib:/usr/local/lib" ./build/unit/unit
+        ./build/unit/unit
+
         cd unit_py
         "${PYTHON_EXECUTABLE}" -m unittest discover -v
 
@@ -122,4 +124,4 @@ jobs:
       with:
         user: __token__
         password: ${{ secrets.PYPI_DEPLOY }}
-        packages_dir: build/pypi/gym_jiminy/dist/
+        packages_dir: build/pypi/gym_jiminy/
