[core] Bundle geometry models in log files for persistence. (#521)
* [core] Fix definition of time unit in log files.
* [core] Fix reading of binary log files.
* [core] Simulation time unit is now fixed to 1e-10.
* [core] Enable serialization of geometry models.
* [core] Refactor telemetry to support binary object dump as constant.
* [core] Use dynamic and non-contiguous memory for telemetry.
* [core] Make logging geometries optional.
* [core] Add option to force loading visual meshes.
* [core] Fix writing log with no data available.
* [python/log] Build robot from logged models.
* [python/viewer] Add option to render marker on background.
* [python/viewer] Fallback to loading geometry if path not available.
* [python/plot] Fig figure sometimes rendered blank.
* [python/plot] Fix figure offscreen rendering.
* [misc] Update easy install dependencies ahead of deployment.
* [misc] Fix python importlib usage.
* [misc] Fix crash if optional python deps are missing.
* [misc] Refactor CI to test building extension from pip install.

Co-authored-by: Alexis Duburcq <alexis.duburcq@wandercraft.eu>

diff --git a/.github/workflows/manylinux.yml b/.github/workflows/manylinux.yml
--- a/.github/workflows/manylinux.yml
+++ b/.github/workflows/manylinux.yml
@@ -8,15 +8,16 @@ on:
   pull_request:
 
 jobs:
-  build-test-and-publish-pypi-manylinux:
-    name: >-
-      (${{ matrix.container }}) (${{ matrix.PYTHON_VERSION }})
-      Build and run the unit tests. Then generate and publish the wheels on PyPi.
+  build-manylinux:
+    name: (${{ matrix.container }}) (${{ matrix.PYTHON_VERSION }}) Build wheels.
 
     strategy:
       matrix:
-        container: ['quay.io/pypa/manylinux2014_x86_64',
-                    'quay.io/pypa/manylinux_2_24_x86_64']
+        container: [
+          'quay.io/pypa/manylinux2014_x86_64:latest',    # Not compatible with CXX11 ABI
+          'quay.io/pypa/manylinux_2_24_x86_64:latest',   # Not compatible with C++17
+          #'quay.io/pypa/manylinux_2_28_poc_x86_64:poc'  # Not compatible with Ubuntu 18.04
+        ]
         PYTHON_VERSION: ['cp36', 'cp37', 'cp38', 'cp39']
 
     runs-on: ubuntu-20.04
@@ -92,7 +93,7 @@ jobs:
 
     #####################################################################################
 
-    - name: Generate and install Python Pip wheels
+    - name: Generate Python Pip wheels
       run: |
         export LD_LIBRARY_PATH="$InstallDir/lib:$InstallDir/lib64:/usr/local/lib"
 
@@ -103,31 +104,98 @@ jobs:
         # built-in option corrupts the shared library for some reason...
         "${PYTHON_EXECUTABLE}" "$RootDir/build_tools/wheel_repair_linux.py" repair \
             -w "$RootDir/build/wheelhouse" "$RootDir/build/pypi/dist/jiminy_py/"*.whl
-        "${PYTHON_EXECUTABLE}" -m pip install --force-reinstall --no-deps "$RootDir/build/wheelhouse/"*.whl
-    - name: Upload the wheel for Linux of Jiminy_py
-      if: success() && github.repository == 'duburcqa/jiminy'
+    - name: Upload the wheel of Jiminy for Linux
       uses: actions/upload-artifact@v1
       with:
-        name: jiminy_py-${{ matrix.PYTHON_VERSION }}-wheel
+        name: wheelhouse
         path: build/wheelhouse
+    - name: Upload the wheels of Gym Jiminy
+      if: success() && matrix.container == 'quay.io/pypa/manylinux2014_x86_64' && matrix.PYTHON_VERSION == 'cp36'
+      uses: actions/upload-artifact@v1
+      with:
+        name: wheelhouse
+        path: build/pypi/dist/gym_jiminy
 
     #####################################################################################
 
-    - name: Publish on PyPi the wheel for Linux of Jiminy_py
-      if: >-
-        success() &&
-        github.repository == 'duburcqa/jiminy' && github.event_name == 'push' && github.ref == 'refs/heads/master'
+  test-user-linux:
+    name: (ubuntu-20.04) Build a pip extension and run the unit tests.
+    needs: build-manylinux
+    runs-on: ubuntu-20.04
+
+    defaults:
+      run:
+        shell: bash -ieo pipefail {0}  # Using bash enables automatic sourcing `.bashrc` and fail-fast behavior
+
+    env:
+      BUILD_TYPE: "Release"
+
+    #####################################################################################
+
+    steps:
+    - name: Checkout jiminy
+      uses: actions/checkout@v2
+    - name: Setup minimal build environment
+      run: |
+        PYTHON_EXECUTABLE="/usr/bin/python3"
+        echo "PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}" >> $GITHUB_ENV
+        echo "RootDir=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
+        echo "InstallDir=${GITHUB_WORKSPACE}/install" >> $GITHUB_ENV
+
+        echo "/home/runner/.local/bin" >> $GITHUB_PATH
+    - name: Installing requirements
+      run: |
+        sudo env "PATH=$PATH" "$RootDir/build_tools/easy_install_deps_ubuntu.sh"
+        sudo apt-get install -y --allow-downgrades --allow-unauthenticated \
+        robotpkg-octomap=1.9.0 robotpkg-urdfdom-headers=1.0.4 robotpkg-hpp-fcl=1.7.1 robotpkg-pinocchio=2.5.6 \
+        robotpkg-py3*-eigenpy=2.6.2 robotpkg-py3*-hpp-fcl=1.7.1 robotpkg-py3*-pinocchio=2.5.6
+
+    #####################################################################################
+
+    - name: Download the wheels previously generated
+      uses: actions/download-artifact@v1
+      with:
+        name: wheelhouse
+        path: wheelhouse
+    - name: Install the wheels previously generated
+      run: |
+        "${PYTHON_EXECUTABLE}" -m pip install --prefer-binary --find-links=wheelhouse jiminy_py
+
+    #####################################################################################
+
+    - name: Build extension module
+      run: |
+        mkdir -p "$RootDir/examples/cpp/pip_extension/build"
+        cd "$RootDir/examples/cpp/pip_extension/build"
+        cmake "$RootDir/examples/cpp/pip_extension" -DCMAKE_INSTALL_PREFIX="$InstallDir" \
+               -DCMAKE_PREFIX_PATH="$InstallDir" -DPYTHON_EXECUTABLE="${PYTHON_EXECUTABLE}" \
+               -DCMAKE_BUILD_TYPE="${BUILD_TYPE}"
+        make install
+
+        "$InstallDir/bin/pip_double_pendulum"
+    - name: Run unit tests on user environment
+      run: |
+        cd "${GITHUB_WORKSPACE}/unit_py"
+        "${PYTHON_EXECUTABLE}" -m unittest discover -v
+
+    #####################################################################################
+
+  publish-pypi-manylinux:
+    name: (Manylinux) Publish on PyPi the wheel for Linux of jiminy_py and gym_jiminy
+
+    needs: test-user-linux
+    runs-on: ubuntu-20.04
+    if: github.repository == 'duburcqa/jiminy' && github.event_name == 'push' && github.ref == 'refs/heads/master'
+
+    steps:
+    - name: Download the wheels previously generated
+      uses: actions/download-artifact@v1
+      with:
+        name: wheelhouse
+        path: wheelhouse
+    - name: Publish the wheels on PyPi
       uses: pypa/gh-action-pypi-publish@master
       with:
         user: __token__
         password: ${{ secrets.PYPI_DEPLOY }}
-        packages_dir: build/wheelhouse
-    - name: Publish on PyPi the wheel of Gym Jiminy (Any platform / Any python3 version)
-      if: >-
-        success() && matrix.container == 'quay.io/pypa/manylinux2014_x86_64' && matrix.PYTHON_VERSION == 'cp36' &&
-        github.repository == 'duburcqa/jiminy' && github.event_name == 'push' && github.ref == 'refs/heads/master'
-      uses: pypa/gh-action-pypi-publish@master
-      with:
-        user: __token__
-        password: ${{ secrets.PYPI_DEPLOY }}
-        packages_dir: build/pypi/dist/gym_jiminy
+        packages_dir: wheelhouse
